version: '3.9'

services:
  mongo-swagger:
    image: mongo:4.4
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=next_db
      - MONGO_INITDB_USERNAME=nextjs
      - MONGO_INITDB_PASSWORD=1234
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - data_nextjs:/data/db
volumes:
  data_nextjs: